import { PageHero } from "@/components/sections/PageHero";
import { LegalDocument, type LegalSection } from "@/components/sections/LegalDocument";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({
  title: "Privacy Policy",
  description: "How HTTPier collects, uses, stores and protects personal information.",
  path: "/privacy",
});

const sections: LegalSection[] = [
  {
    id: "information-we-collect",
    title: "Information we collect",
    paragraphs: ["We collect information you choose to provide and limited technical information generated when you use the website."],
    items: [
      "Contact and identity details, including your name, company and email address.",
      "Project information, including your goals, project type, estimated budget, preferred timeline and any details you add to an enquiry.",
      "Communications and records of our correspondence if you contact or work with us.",
      "Basic technical records that may be generated by our hosting infrastructure, such as IP address, browser type, requested page, referring page, timestamp and security logs.",
    ],
  },
  {
    id: "how-we-use-information",
    title: "How we use information",
    items: [
      "Respond to enquiries and understand whether HTTPier is a suitable fit for your project.",
      "Prepare proposals, estimates and project plans you request.",
      "Communicate about a current or potential engagement and provide contracted services.",
      "Operate, secure, diagnose and improve the website and prevent misuse.",
      "Maintain necessary business records and comply with legal obligations.",
    ],
    paragraphs: ["We process personal information for the purpose explained when it is collected, with consent where required, to take steps you request before entering a contract, to perform an agreement, or where otherwise permitted by applicable law."],
  },
  {
    id: "contact-form",
    title: "Contact-form data",
    paragraphs: [
      "Submitting the contact form sends the information entered to HTTPier for enquiry handling. Please do not include passwords, payment-card information, health records, government identifiers or other sensitive personal information in the project-details field.",
      "Sending an enquiry does not create a client relationship or require either party to proceed with a project.",
    ],
  },
  {
    id: "cookies-and-analytics",
    title: "Cookies and analytics",
    paragraphs: [
      "HTTPier does not currently use advertising trackers, behavioural profiling tools or third-party analytics on this website. The site does not intentionally set non-essential cookies.",
      "Our hosting and security infrastructure may process standard request metadata and use strictly necessary technical mechanisms to deliver and protect the site. If we introduce analytics or non-essential cookies, this policy will be updated and any consent required by law will be requested before they are used.",
    ],
  },
  {
    id: "sharing-and-providers",
    title: "Third-party providers",
    paragraphs: ["We do not sell or rent personal information. We may share only what is reasonably necessary with service providers that help operate the website or business, subject to appropriate confidentiality and data-protection obligations."],
    items: [
      "Website hosting, content delivery, infrastructure and security providers.",
      "Email and communication providers used to receive and respond to enquiries.",
      "Project-management, document, accounting or professional-advisory providers used for an engagement.",
      "Authorities or other parties where disclosure is required by law, needed to protect legal rights, or connected with a legitimate business restructuring.",
    ],
  },
  {
    id: "storage-and-security",
    title: "Storage and security",
    paragraphs: [
      "Information may be stored in systems operated by HTTPier and trusted service providers. Depending on the provider, processing may occur in India or another country where the provider operates. Where required, we use contractual or other appropriate safeguards for such processing.",
      "We use reasonable technical, administrative and organisational measures designed to protect information against unauthorised access, alteration, disclosure and loss. No internet transmission or storage system can be guaranteed to be completely secure.",
    ],
  },
  {
    id: "retention",
    title: "Retention",
    paragraphs: [
      "Enquiry information is normally retained for up to 24 months after the last meaningful interaction so we can follow up, maintain context and manage business records. If an enquiry becomes a client project, relevant information may be retained for the duration of the engagement and afterwards as required for contracts, accounts, dispute resolution or legal compliance.",
      "Technical and security logs are retained according to operational need and the schedules of the relevant infrastructure provider. Information is deleted or anonymised when it is no longer reasonably required, unless a longer period is required by law.",
    ],
  },
  {
    id: "your-rights",
    title: "Your choices and rights",
    paragraphs: [
      "Depending on the law that applies to you, you may request access to information we hold about you, correction of inaccurate information, deletion, withdrawal of consent, or information about how your data has been used. You may also raise a grievance and, where applicable, nominate another person to exercise your rights.",
      "To make a request, use the contact form or call the number below. We may need to verify your identity before acting. Some information may be retained where necessary to comply with law, establish or defend legal claims, or complete an agreement.",
    ],
  },
  {
    id: "children",
    title: "Children's privacy",
    paragraphs: ["This website is intended for business users and is not directed to children. HTTPier does not knowingly collect personal information from anyone under 18 through this website. If you believe a child has submitted information, contact us so it can be reviewed and removed where appropriate."],
  },
  {
    id: "external-links",
    title: "External links",
    paragraphs: ["The website contains links to client projects and third-party services. Their privacy practices are controlled by their respective operators, and this policy does not apply once you leave httpier.in."],
  },
  {
    id: "policy-changes",
    title: "Changes to this policy",
    paragraphs: ["We may update this policy when the website, our processing practices or applicable requirements change. The revised version will be published here with a new last-updated date. Material changes may also be highlighted on the website where appropriate."],
  },
  {
    id: "contact",
    title: "Contact and grievances",
    paragraphs: ["HTTPier is responsible for the personal information described in this policy. Privacy questions, requests or grievances can be submitted through the contact page at httpier.in/contact or by calling +91 9489813846. We will acknowledge and address requests within a reasonable period and in accordance with applicable law."],
  },
];

export default function PrivacyPage() {
  return (
    <>
      <PageHero eyebrow="Legal" title="Privacy Policy" description="A clear account of what HTTPier collects, why we use it and the choices available to you." />
      <LegalDocument
        updated="9 September 2026"
        introduction="This Privacy Policy explains how HTTPier collects and handles personal information when you visit httpier.in, submit a project enquiry or otherwise communicate with us."
        summary={[
          "We collect only the information needed to respond to enquiries, plan projects and operate the website.",
          "We do not currently use advertising trackers or third-party analytics.",
          "We do not sell personal information.",
          "You can ask to access, correct or delete your information, subject to applicable law.",
        ]}
        sections={sections}
      />
    </>
  );
}
